[package]
name = "las-cleanup"
version = "0.0.2"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86" }
clap = { version = "4.5.8", features = ["derive"] }
las = { version = "0.8.8" }
uuid = { version = "1.9.1", features = ["v4"] }
